config/routes.rb
Rails.application.routes.draw do
  resources :news, only: :index
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
  end
  resources :users, only: [:show, :edit, :update]
  resources :articles
  resources :articles do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  root "articles#index"
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { maximum: 64 }
  validates :content, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_rich_text :content
  attachment :image
  enum category: { blog: 0, maintenance_note: 1 }

  scope :show_blog, -> { where(category: 0) }
  scope :show_maintenance_note, -> { where(category: 1) }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :find_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.eager_load(:user).order(created_at: :desc).paginate(page: params[:page], per_page: 9).with_rich_text_content
    #ソート機能
    if params[:show_blog]
      @articles = @articles.show_blog
    elsif params[:show_maintenance_note]
      @articles = @articles.show_maintenance_note
    end
  end

  def show
    @user = @article.user
    @comments = @article.comments
    if user_signed_in?
     @comment = current_user.comments.new
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      redirect_to @article, notice: "記事を投稿しました"
    else
      render :new, status: :unprocessable_entity
    end

  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: "記事を更新しました"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit
    unless @article.user == current_user
      redirect_to root_path, alert: "他人の記事を編集することは出来ません"
    end
  end
  
  def destroy
    @article.destroy
      redirect_to root_path, notice: "記事を削除しました"
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:image, :category, :title, :content)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<% provide(:button_text, '編集を保存') %>
<%= render "devise/shared/error_messages", resource: @article %>

<h1 class="text-center" style="margin-top: 10px">記事の編集</h1>

<div class="col-md-6 col-md-offset-3 new-article">
  <% if @article.image_id.present? %>
  <%= attachment_image_tag @article, :image, class: 'img-responsive center-block', style: "width: 100%" %>
  <% end %>
  <%= form_with(model:@article, data: {controller: "emoji-picker"}) do |f| %>
    <%= render '/layouts/form', f: f %>
  <% end %>
  <div class="delete-button">
    <%= link_to article_path(@article), 
                data: { "turbo-method": :delete, turbo_confirm: "記事を削除します。よろしいですか？" } do %>
      <i class="far fa-trash-alt"></i>
    <% end %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="home-title">
  <div><h1><%= link_to '新規記事一覧', root_path %></h1></div>
  <div class="row sort">
    <ul>
      <li><%= link_to '新着', root_path %></li>
      <li class="sort-item"><%= link_to 'ブログ', root_path(show_blog: "true") %></li>
      <li><%= link_to '整備', root_path(show_maintenance_note: "true") %></li>
    </ul>
  </div>
</div>

<div class="row">
  <% @articles.each do |article| %>
    <div class="col-12 col-sm-6 col-lg-4" style="padding: 20px">
      <div class="card mb-1 card-list">
        <div class="card-image">
          <%= link_to article do %>
            <%= attachment_image_tag article, :image, fallback: "no_image.png", class: 'article-images' %>
          <% end %>
        </div>
        <div class="card-body" style="padding: 12px">
          <p class="card-text" style="font-size: 24px"><%= link_to article.title.truncate(30), article_path(article) %></p>
          <p class="card-text">
            <%= strip_tags(article.content.to_s).gsub(/[\n]/,"").strip.truncate(40) %>
            <% if strip_tags(article.content.to_s).gsub(/[\n]/,"").strip.length > 40 %>
              <%= link_to "続きを読む", article_path(article), class: 'link' %>
            <% end %>
            <div class="info m-2">
              <a class="link" data-turbo="false" style="margin-right: 3px" href="/users/<%= article.user.id %>">
                @<%= article.user.name %>
              </a>
              <p><%= article.created_at.strftime("%Y年%m月%d日") %></p>
            </div>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="paginator">
  <%= paginate @articles %>
</div>

app/views/articles/new.html.erb
<% provide(:button_text, '新規作成') %>
<%= render "devise/shared/error_messages", resource: @article %>

<h1 class="text-center" style="margin-top: 10px">記事の新規作成</h1>

<div class="col-md-6 col-md-offset-3 new-article">
  <%= form_with(model:@article, data: {controller: "emoji-picker"}) do |f| %>
    <div id="cover-image" class="form-group">
      <p style="margin: 0px">サムネイル</p>
      <%= image_tag 'no_image.png', class: 'article-image' %>
    </div>
    <%= f.file_field :image %>
    <div class="categories" style="margin-top: 10px">
      <p style="margin:0">カテゴリ</p>
      <%= f.radio_button :category, :blog %>
      <%= f.label :category_blog, 'ブログ' %>
      <%= f.radio_button :category, :maintenance_note %>
      <%= f.label :category_maintenance_note, '整備記録' %>
    </div>
    <%= render '/layouts/form', f: f %>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="row" style="border-left: 1px solid rgba(0,0,0,.125)">

  <div class="col-sm-3 article-sidebar">
    <div class="sidebar">
      <h3 class="sideMenuTitle">投稿者</h3>
      <%= attachment_image_tag @user, :profile_image, fallback: "default.png",
                                                     class: 'img-responsive center-block profile-image' %>
      <h3 style="text-align: center" data-turbo="false"><%= link_to @user.name, user_path(@user) %></h3>
      <%= @user.self_introduction %>
    </div>
  </div>

  <div class="col-sm-9 article-show">
    <% if @article.image_id.present? %>
      <%= attachment_image_tag @article, :image, class: 'main-image' %>
    <% end %>
    <div class="content">
      <h3 class="title"><%= @article.title %></h3>
      <!-- リッチテキストエディタ -->
      <%= @article.content %>
      <% if user_signed_in? && @article.user_id == current_user.id %>
        <%= link_to '編集', edit_article_path(@article), class: 'btn btn-primary' %>
      <% end %>
      <!-- いいね機能 -->
      <div class="likes" id="like_<%= @article.id %>">
        <%= render 'likes/like', article: @article %>
      </div>
      <p style="text-align: right">投稿日:<%= @article.created_at.strftime("%Y年%m月%d日") %></p>
    </div>

    <!-- コメント機能 -->
    <div class="comment-field">

      <% if user_signed_in? %>
        <div class="new-comment" id="comments-area">
          <%= form_with(model:[@article, @comment], method: :article) do |f| %>
            <%= f.text_area :comment_content, rows:'2', placeholder: "コメントする", style: "width: 100%" %>
            <%= f.hidden_field :article_id, value: @article.id %> 
            <%= f.submit "送信" %>
          <% end %>
        </div>
      <% end %>

      <% @comments.each do |comment| %>
        <div class="comment">
          <div class="comment-user">
            <%= attachment_image_tag comment.user, :profile_image, fallback: "default.png",
                                                      class: 'img-responsive center-block comment-user-img' %>
            <a data-turbo="false" href="/users/<%= comment.user.id %>" style="padding-left: 2%"><%= comment.user.name %></a>
            <% if user_signed_in? && comment.user_id == current_user.id %>
              <%= link_to article_comment_path(comment.article, comment), style: "margin-left: auto",
                                              data: { "turbo-method": :delete, turbo_confirm: "コメントを削除しますか？" } do %>
                <i class="far fa-trash-alt"></i>
              <% end %>
            <% end %>
          </div>
          <%= comment.comment_content %>
          <p class="article-comment"><%= comment.created_at.strftime("%Y年%m月%d日") %></p>
        </div>
      <% end %>

    </div>
  </div>
</div>