config/routes.rb
Rails.application.routes.draw do
  resources :news, only: :index
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
  end
  resources :users, only: [:show, :edit, :update]
  resources :articles
  resources :articles do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  root "articles#index"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_article

  def create
    @like = Like.new(user_id: current_user.id, article_id: @article.id)
    @like.save
    redirect_to article_path(params[:article_id]) 
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, article_id: @article.id)
    @like.destroy
    redirect_to article_path(params[:article_id]) 
  end
  
  private

    def set_article
      @article = Article.find_by(id: params[:article_id])
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if current_user.likes.find_by(article_id: @article.id) %>
    <%= link_to article_likes_path(@article.id), data: { "turbo-method": :delete } do %>
      <i class="fas fa-thumbs-up liked"></i>
      <%= @article.likes.count %>
    <% end %>
  <% else %>
    <%= link_to article_likes_path(@article.id), data: { "turbo-method": :post } do %>
      <i class="far fa-thumbs-up"></i>
      <%= @article.likes.count %>
    <% end %>
  <% end %>
<% else%>
  <%= link_to new_user_session_path do %>
    <i class="far fa-thumbs-up"></i>
    <%= @article.likes.count %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$('#like_#{@article.id}').html("#{escape_javascript(render "likes/like", article: @article )}");

app/views/likes/destroy.js.erb
$('#like_#{@article.id}').html("#{escape_javascript(render "likes/like", article: @article )}");