config/routes.rb
Rails.application.routes.draw do
  resources :news, only: :index
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
  end
  resources :users, only: [:show, :edit, :update]
  resources :articles
  resources :articles do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { maximum: 64 }
  validates :content, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_rich_text :content
  attachment :image
  enum category: { blog: 0, maintenance_note: 1 }

  scope :show_blog, -> { where(category: 0) }
  scope :show_maintenance_note, -> { where(category: 1) }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :comment_content, presence: true, length: { maximum:140 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 32 }
  validates :email, { presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false } }
  
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_articles, through: :likes, source: :article
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :find_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.eager_load(:user).order(created_at: :desc).paginate(page: params[:page], per_page: 9).with_rich_text_content
    #ソート機能
    if params[:show_blog]
      @articles = @articles.show_blog
    elsif params[:show_maintenance_note]
      @articles = @articles.show_maintenance_note
    end
  end

  def show
    @user = @article.user
    @comments = @article.comments
    if user_signed_in?
     @comment = current_user.comments.new
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      redirect_to @article, notice: "記事を投稿しました"
    else
      render :new, status: :unprocessable_entity
    end

  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: "記事を更新しました"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit
    unless @article.user == current_user
      redirect_to root_path, alert: "他人の記事を編集することは出来ません"
    end
  end
  
  def destroy
    @article.destroy
      redirect_to root_path, notice: "記事を削除しました"
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:image, :category, :title, :content)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_to article_path(@article), notice: 'コメントを投稿しました'
    else
      redirect_to article_path(@article), alert: 'コメントは1文字以上140文字以下にしてください'
    end
  end

  def destroy
    Comment.find_by(id: params[:id], article_id: params[:article_id]).destroy
    redirect_to article_path(params[:article_id]), notice: 'コメントを削除しました'
  end

  private

  def comment_params
    params.require(:comment).permit(:comment_content, :article_id)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_article

  def create
    @like = Like.new(user_id: current_user.id, article_id: @article.id)
    @like.save
    redirect_to article_path(params[:article_id]) 
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, article_id: @article.id)
    @like.destroy
    redirect_to article_path(params[:article_id]) 
  end
  
  private

    def set_article
      @article = Article.find_by(id: params[:article_id])
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :authenticate_user!, except: :index
  require 'news-api'
  require 'will_paginate/array'
  
  def index
    news = News.new(ENV['NEWS_API_KEY'])
    @news = news.get_everything(q: '%E3%83%90%E3%82%A4%E3%82%AF', sortBy: "popularity").paginate(
                                                                    page: params[:page], per_page: 18)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :find_user

  def show
    @articles = @user.articles.order(created_at: :desc).paginate(page: params[:page], per_page: 9).with_rich_text_content
  end

  def edit
    unless @user.id == current_user.id
      redirect_to root_path, alert: "他人のアカウントを編集することは出来ません"
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html{ redirect_to :user }
        format.js
      else
        format.html { render :user }
        format.js
      end
    end
  end

  def destroy
    @user.destroy
      redirect_to root_path, notice: "アカウントを削除しました"
  end

  private
  
  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :self_introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_alert(key)
    case key
    when "alert"
      "danger"
    when "notice"
      "info"
    when "success"
      "success"
    when "error"
      "danger"
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_data.html.erb
<div class="col-12 col-sm-6 col-lg-4" style="padding: 20px">
  <div class="card mb-1 card-list">
    <div class="card-image">
      <%= link_to news.url do %>
        <% if news.urlToImage.present? %>
          <%= image_tag(news.urlToImage, class: 'article-images') %>
        <% else %>
          <%= image_tag("no_image.png", class: 'article-images') %> 
        <% end %>
      <% end %>
    </div>
    <div class="card-body" style="padding: 12px">
      <p class="card-text" style="font-size: 24px"><%= link_to news.title.truncate(30), news.url %></p>
      <p class="card-text">
        <%= strip_tags(news.description.to_s).gsub(/[\n]/,"").strip.truncate(40) %>
        <% if strip_tags(news.description.to_s).gsub(/[\n]/,"").strip.length > 40 %>
          <%= link_to "続きを読む", news.url, class: 'link' %>
        <% end %>
        <div class="info m-2">
          <p style="margin-right: 3px">
            <%= news.name %> <%= time_ago_in_words(news.publishedAt) %>前
          </p>
        </div>
      </p>
    </div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= bootstrap_alert(key) %>">
    <strong>
      <%= value %>
    </strong>
  </div>
<% end %>

app/views/layouts/_form.html.erb
<div class="form-group">
  <%= f.label :title , 'タイトル', style: "margin-top: 10px" %>
  <%= f.text_field :title, class: "form-control" %>
</div>

<%= content_tag(:div, "", class:"pickerContainer", data: {
  emoji_picker_target: "pickerContainer"
}) %>
<div class="field">
  <%= f.label :content, '内容', style: "margin-top: 10px" %>
  <%= f.rich_text_area :content, data: {
    emoji_picker_target: "trixEditor"
  } %>
</div>

<%= f.submit yield(:button_text), class: "btn btn-primary new-button" %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-sm navbar-light">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="/" style="color:white">motolife</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                                 aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to "ホーム", root_path %></li>
            <li><%= link_to "ニュース", news_index_path %></li>
            <li><%= link_to "ブログ作成", new_article_path %></li>
            <li data-turbo="false"><%= link_to current_user.name, user_path(current_user) %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, data: { "turbo-method": :delete,
                                                                    turbo_confirm: "モトlifeからログアウトしますか？" } %></li>
          <% else %>
            <li><%= link_to "ホーム", root_path %></li>
            <li><%= link_to "ニュース", news_index_path %></li>
            <li><%= link_to "ブログ作成", new_article_path %></li>
            <li><%= link_to "新規登録", new_user_registration_path %></li>
            <li><%= link_to "ログイン", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  
</header>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>motolife</title>
    <%= favicon_link_tag('favicon.ico') %>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="//cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="//code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <%= render '/layouts/flash' %>
      <%= yield %>
    </div>
  </body>
</html>